services:
  rhiva-ag:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
      - "8000-8005:8000-8005"
    networks:
      - webnet
    env_file: .env
    environment:
      REDIS_URL: ${REDIS_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
networks:
  webnet:
    driver: bridge
    external: true